/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** PDF 轉圖片 */
export declare class PdfToImage {
  /**
   * 初始化 PDF 轉圖片流程
   *
   * # Parameters
   * - `pdf_path`：**必要參數**，欲開啓的 PDF 檔案路徑，絕對/相對路徑均可接受
   * - `password`：選填參數， PDF 檔案密碼
   *
   * # Errors
   * 1. `pdf_path` 參數使用相對路徑時，無法取得標準化的 PDF 檔案路徑
   * 2. PDF 檔案已加密，提供的密碼無效
   * 3. 檔案名稱不存在
   * 4. 無法取得當前系統時間
   */
  constructor(pdfPath: string, password?: string | undefined | null)
  /**
   * 將初始化的 PDF 檔案轉換為圖片
   *
   * *目前僅支援輸出 PNG 格式*
   *
   * # Parameters
   * - `path`：**必要參數**，轉換圖片的存放目標路徑
   * - `dpi`：選填參數，每英吋點數，此數值越高，產生出來的圖片品質與檔案大小越大，預設為 `150.0`
   *
   * # Errors
   * 1. 無法取得標準化的存放目標路徑
   * 2. 無法建立輸出 PNG 檔
   * 3. 無法建立暫存檔
   * 4. 無法建立 PDF 表面（PDF surface ，渲染畫面用）
   * 5. 無法利用產生出的 PDF 表面建立渲染參數
   * 6. 無法拉伸渲染畫面至指定的 DPI 大小
   * 7. 無法渲染 PDF 背景色
   * 8. 無法將渲染出的畫面寫入至 PNG 檔
   */
  toImage(path: string, dpi?: number | undefined | null): Array<string>
}
